"""empty message

Revision ID: 5c3f885cc7ce
Revises: bbc5e6d9dec0
Create Date: 2023-05-27 17:54:12.773050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c3f885cc7ce'
down_revision = 'bbc5e6d9dec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Workorder', sa.Column('State', sa.Boolean(), nullable=False, comment='工单状态'))
    op.add_column('Workorder', sa.Column('Notes', sa.String(length=100), nullable=True, comment='处理后备注'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Workorder', 'Notes')
    op.drop_column('Workorder', 'State')
    # ### end Alembic commands ###
