"""empty message

Revision ID: 772c4f6ab3ac
Revises: 5c3f885cc7ce
Create Date: 2023-09-11 21:04:05.472080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '772c4f6ab3ac'
down_revision = '5c3f885cc7ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Workorder', 'UserId',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_comment='工单阳光跑userid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Workorder', 'UserId',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_comment='工单阳光跑userid')
    # ### end Alembic commands ###
