"""empty message

Revision ID: 8ebcc352c429
Revises: e588d5364e9d
Create Date: 2023-09-20 20:40:37.821407

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ebcc352c429'
down_revision = 'e588d5364e9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Workorder', sa.Column('MsgList', sa.String(length=255), nullable=False, comment='消息列表'))
    op.alter_column('Workorder', 'CheckStatus',
               existing_type=mysql.INTEGER(display_width=11),
               comment='工单查看状态：0未查看1已查看',
               existing_comment='工单查看状态：0未查看或未回复1已查看或已回复',
               existing_nullable=False)
    op.drop_column('Workorder', 'Notes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Workorder', sa.Column('Notes', mysql.VARCHAR(length=100), nullable=True, comment='处理后备注'))
    op.alter_column('Workorder', 'CheckStatus',
               existing_type=mysql.INTEGER(display_width=11),
               comment='工单查看状态：0未查看或未回复1已查看或已回复',
               existing_comment='工单查看状态：0未查看1已查看',
               existing_nullable=False)
    op.drop_column('Workorder', 'MsgList')
    # ### end Alembic commands ###
