"""empty message

Revision ID: 9854595cef97
Revises: 84830215d86f
Create Date: 2023-04-03 20:49:59.841202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9854595cef97'
down_revision = '84830215d86f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SystemLog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('LogContent', sa.TEXT(length=200), nullable=False, comment='日志内容'),
    sa.Column('LogLib', sa.String(length=50), nullable=False, comment='日志的类别'),
    sa.Column('UserName', sa.String(length=100), nullable=False, comment='网站用户名'),
    sa.Column('Time', sa.DateTime(), nullable=False, comment='创建消息的时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SystemLog')
    # ### end Alembic commands ###
