"""empty message

Revision ID: b9294ba2beda
Revises: 7d1fe0e58de8
Create Date: 2023-03-25 09:07:02.702473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9294ba2beda'
down_revision = '7d1fe0e58de8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('WebConfig', sa.Column('AndroidAppUpContext', sa.String(length=255), nullable=True, comment='软件更新内容'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('WebConfig', 'AndroidAppUpContext')
    # ### end Alembic commands ###
