"""empty message

Revision ID: ba66dfe29823
Revises: 772c4f6ab3ac
Create Date: 2023-09-11 21:16:50.842608

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba66dfe29823'
down_revision = '772c4f6ab3ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Workorder', sa.Column('WorkorderContent', sa.String(length=255), nullable=False, comment='工单内容'))
    op.drop_column('Workorder', 'WorkContent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Workorder', sa.Column('WorkContent', mysql.VARCHAR(length=255), nullable=False, comment='工单内容'))
    op.drop_column('Workorder', 'WorkorderContent')
    # ### end Alembic commands ###
