"""empty message

Revision ID: c68bd4bfe744
Revises: b9294ba2beda
Create Date: 2023-03-25 22:30:23.750863

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c68bd4bfe744'
down_revision = 'b9294ba2beda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('WebConfig', 'AppDownloadUrl')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('WebConfig', sa.Column('AppDownloadUrl', mysql.VARCHAR(length=200), nullable=False, comment='APP下载地址'))
    # ### end Alembic commands ###
