"""empty message

Revision ID: d6baf227f93d
Revises: 9854595cef97
Create Date: 2023-05-27 17:09:07.606915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd6baf227f93d'
down_revision = '9854595cef97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workorder',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('User', sa.String(length=100), nullable=False, comment='网站账号'),
    sa.Column('AdminUser', sa.String(length=50), nullable=False, comment='上级用户名'),
    sa.Column('UseUserId', sa.Integer(), nullable=False, comment='工单阳光跑userid'),
    sa.Column('WorkContent', sa.String(length=255), nullable=False, comment='工单内容'),
    sa.Column('Time', sa.DateTime(), nullable=False, comment='创建工单的时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.alter_column('IMEICodes', 'User',
               existing_type=mysql.VARCHAR(length=100),
               comment='网站账号',
               existing_comment='代理账号',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('IMEICodes', 'User',
               existing_type=mysql.VARCHAR(length=100),
               comment='代理账号',
               existing_comment='网站账号',
               existing_nullable=False)
    op.drop_table('workorder')
    # ### end Alembic commands ###
