"""empty message

Revision ID: e588d5364e9d
Revises: 835ba67af8df
Create Date: 2023-09-12 14:41:47.510070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e588d5364e9d'
down_revision = '835ba67af8df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Workorder', sa.Column('CheckStatus', sa.Integer(), nullable=False, comment='工单查看状态：0未查看或未回复1已查看或已回复'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Workorder', 'CheckStatus')
    # ### end Alembic commands ###
